name: Upload
on:
  push:
    branches:
      - master
env:
  SCREEPS_TOKEN: ${{secrets.SCREEPS_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: '24'
      - run: npm run push-main
      
